version: "3.9"

services:
  redis:
    networks:
      - local-shared-network
    image: redis:alpine3.19
    command: /bin/sh -c "redis-server --requirepass redis"
    ports:
      - "6379:6379"

networks:
  local-shared-network:
    external: true
