version: "3.9"

services:
  clickhouse:
    networks:
      - local-shared-network
    image: bitnami/clickhouse:latest 
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - CLICKHOUSE_ADMIN_USER=clickhouse
      - CLICKHOUSE_ADMIN_PASSWORD=password
    ports:
      - "9000:9000"
      - "8123:8123"

networks:
  local-shared-network:
    external: true
