version: "3.9"

services:
  elasticsearch:
    networks:
      - local-shared-network
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.9.2"
    environment:
      - discovery.type=single-node 
    ports:
      - "9200:9200"
    volumes:
      - type: volume
        source: elasticsearch_data
        target: /usr/share/elasticsearch/data

volumes:
  elasticsearch_data:

networks:
  local-shared-network:
    external: true

